### ISSUE TITLE
Link to supercharge.info map not using site ID

### ISSUE THREAD

**Issue by Dani21** [supercharge-info/supercharge.info-admin#19]
The site links in the site edit list isn't using the newer style site ID link. Instead they use the old style GPS and zoom parameters:

![Uses GPS and zoom still](https://github.com/supercharge-info/supercharge.info-admin/assets/1804643/11241cad-7e0c-4ec7-a615-e8368bae99ca)

**Comment by paulkva** [comment]
Done as part of #24
